# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Book  Name')),
                ('author', models.CharField(max_length=100, verbose_name='Book Author')),
                ('content', models.CharField(max_length=1000, verbose_name='Book Content')),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 9, 17, 9, 1, 15, 992402), verbose_name='Book Creation Time')),
                ('expiry', models.DateTimeField(default=datetime.datetime(2017, 9, 17, 9, 2, 15, 992402), verbose_name='Book URL Expiry Time')),
            ],
        ),
    ]
