# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_auto_20170917_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 17, 20, 53, 47, 319004), verbose_name='Book Creation Time'),
        ),
        migrations.AlterField(
            model_name='book',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 17, 20, 54, 47, 319004), verbose_name='Book URL Expiry Time'),
        ),
    ]
