# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_auto_20170917_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 17, 21, 12, 55, 492297), verbose_name='Book Creation Time'),
        ),
        migrations.AlterField(
            model_name='book',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 17, 21, 13, 55, 492297), verbose_name='Book URL Expiry Time'),
        ),
    ]
