# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_auto_20170917_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='expiry',
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Book Creation Time'),
        ),
    ]
